### ISSUE TITLE
default books folder

### ISSUE THREAD

**Issue by Fuzzwah** [mattbnz/kindle-utils#1]
In the doco you mentioned that the default location for the book_stats.py script to look for was:

/media/Kindle/documents

But digging into the code I see that it is actually set to:

~/kindle-books

Which actually gets me wondering if you've managed to get sshfs set up so the script can do this lookup via wifi rather than having to have the kindle connected via USB. This is actually what I'm trying to get working, but I'm having issues running sshfs as a non-root user.

**Comment by mattbnz** [comment]
Nothing that fancy sorry, I just rsync the files to a local directory. I'll update the docs/code to match.
