### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by angoodkind** [mattbnz/kindle-utils#4]
This looks ideal for my purposes of tracking reading data. Before starting in, I was just curious if there is an updated version, since there have been many updates to the kindle.

**Comment by mattbnz** [comment]
No updates, I haven't managed to get it working reliably with my Paperwhite, Amazon keeps changing things and making it harder and harder to jailbreak the devices. :(

If you get it working, please send pull requests, I'll gladly accept them.

**Comment by angoodkind** [comment]
Ok, thanks!
